name: Integration Workflow

on: 
  workflow_dispatch:
   inputs:
     application:
       description: 'Application Services'
       type: string
     load: 
       description: 'Workload Size'
       type: string
     name:
       description: 'Name'
       type: string
     region: 
       description: 'Region'
       type: string
     change: 
       description: 'Change ID'
       type: string  
     changesys: 
       description: 'Change Sys ID'
       type: string 
     env:
       description: 'Environment'
       type: string
jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - run: echo "${{ inputs.application }}\n${{ inputs.load}}\n${{ inputs.name }}\n${{ inputs.region }}\n${{ inputs.change}}\n${{ inputs.changesys }}\n${{ inputs.env }}"
      
