name: Integration Workflow

on: 
  workflow_dispatch:
   inputs:
     application:
       description: 'Application Services'
       type: string
     load: 
       description: 'Workload Size'
       type: string
     name:
       description: 'Name'
       type: string
     region: 
       description: 'Region'
       type: string
     change: 
       description: 'Change ID'
       type: string  
     changesys: 
       description: 'Change Sys ID'
       type: string 
     env:
       description: 'Environment'
       type: string
jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - run: echo "${{ inputs.application }}"
      - run: echo "${{ inputs.load}}"
      - run: echo "${{ inputs.name }}"
      - run: echo "${{ inputs.region }}"
      - run: echo "${{ inputs.change}}"
      - run: echo "${{ inputs.changesys }}"
      - run: echo "${{ inputs.env }}"
      
